version: '3'
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - D:\docker\redis\redis.conf:/etc/redis/redis.conf
      - D:\docker\redis\data:/data
    environment:
      - REDIS_PASSWORD=root
    networks:
      - sc-net
    ports:
      - 6379:6379
    env_file: .env

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    volumes:
      - D:\docker\rabbitmq\data:/var/lib/rabbitmq
    networks:
      - sc-net
    ports:
      - 5672:5672
      - 15672:15672
    env_file: .env

networks:
  sc-net:
    external: false
