version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      - D:\docker\jenkins\jenkins_home/:/var/jenkins_home
      - D:\docker\jenkins\docker.sock:/var/run/docker.sock
      - D:\docker\jenkins\docker:/usr/bin/docker
      - D:\docker\jenkins\x86_64-linux-gnu\libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    ports:
      - 8029:8080
    expose:
      - 8080
      - 50000
    privileged: true
    user: root
    restart: always
    container_name: jenkins
    environment:
      JAVA_OPTS: '-Djava.util.logging.config.file=/var/jenkins_home/log.properties'
